In [14]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

base = pd.read_csv('iris.csv')
previsores = base.iloc[:, 0:4].values
classe = base.iloc[:, 4].values

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size=0.25)

In [19]:
classificador = Sequential()
classificador.add(Dense(units = 4, activation = 'relu', input_dim = 4))
classificador.add(Dense(units = 4, activation = 'relu'))
classificador.add(Dense(units = 3, activation = 'softmax'))

In [21]:
classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])
classificador.fit(previsores_treinamento, classe_treinamento, batch_size = 10, epochs = 1000)

Epoch 1/1000

12/12 [==============================] - 4s 19ms/step - loss: 1.1165 - categorical_accuracy: 0.3304
Epoch 2/1000
12/12 [==============================] - 0s 13ms/step - loss: 1.1041 - categorical_accuracy: 0.3304
Epoch 3/1000
12/12 [==============================] - 0s 14ms/step - loss: 1.1014 - categorical_accuracy: 0.3304
Epoch 4/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.0981 - categorical_accuracy: 0.3304
Epoch 5/1000
12/12 [==============================] - 0s 13ms/step - loss: 1.0971 - categorical_accuracy: 0.3304
Epoch 6/1000
12/12 [==============================] - 0s 10ms/step - loss: 1.0963 - categorical_accuracy: 0.3304
Epoch 7/1000
12/12 [==============================] - 0s 13ms/step - loss: 1.0956 - categorical_accuracy: 0.2857
Epoch 8/1000
12/12 [==============================] - 0s 12ms/step - loss: 1.0947 - categorical_accuracy: 0.1518
Epoch 9/1000
12/12 [==============================] - 0s 13ms/step - loss: 1.0947 - categorical

In [22]:
print(classificador.evaluate(previsores_teste, classe_teste))

2/2 [==============================] - 1s 32ms/step - loss: 0.0790 - categorical_accuracy: 1.0000
[0.07904078811407089, 1.0]


In [25]:
from sklearn.metrics import confusion_matrix
import numpy as np

previsoes = classificador.predict(previsores_teste)
previsoes = (previsoes > 0.5)
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

print(confusion_matrix(previsoes2, classe_teste2))

2/2 [==============================] - 0s 5ms/step
[[ 9  0  0]
 [ 0 13  0]
 [ 0  0 16]]
